wandb_version: 1

model:
  value:
    model_name: PreActResNet18-CIFAR100
optimizer:
  value:
    params:
      lr: 0.001
      weight_decay: 0.05
    type: AdamW
transform:
  value:
    RandomCrop:
      padding: 4
      size: 32
    RandomHorizontalFlip: null
